[fonts.en]
    title = "Palatino"
    author = "Times New Roman"
    footer = "Georgia"
    contents = "Georgia"
    context = "Georgia"
    math = "Times New Roman"
    ending = "Palatino"

[fonts.zh]
    title = "STKaiti"
    author = "Kaiti SC"
    footer = "Songti SC"
    contents = "Songti SC"
    context = "Songti SC"
    math = "Kaiti SC"
    ending = "STKaiti"

[sizes]
    author = 14
    title = 40
    context = 10.5
    footer = 10
    ending = 50

[spaces]
    par-indent = 2
    par-leading = 1
    par-spacing = 1
    list-indent = 1.2
    block-above = 1
    block-below = 1
    contents-indent = 2

[colors]
    # heading level 1
    primary = "#fcbd00"
    primary-light = "#d6c6b7"
    primary-lightest = "#fcbd00"
    primary-dark = "#fcbd00"
    primary-darkest = "#fcbd00"
    # heading level 2
    secondary = "#3297df"
    secondary-light = "#ff0000"
    secondary-lightest = "#3297df"
    secondary-dark = "#3297df"
    secondary-darkest = "#3297df"
    # heading level 3
    tertiary = "#448C95"
    tertiary-light = "#3297df"
    tertiary-lightest = "#3297df"
    tertiary-dark = "#3297df"
    tertiary-darkest = "#3297df"
    # content
    neutral = "#3297df"
    neutral-light = "#3297df"
    neutral-lightest = "#fafafa"
    neutral-dark = "#202020"
    neutral-darkest = "#000000"
