[fonts.en]
    title = "Palatino"
    author = "Times New Roman"
    footer = "Georgia"
    contents = "Georgia"
    context = "Georgia"
    math = "Times New Roman"
    ending = "Palatino"

[fonts.zh]
    title = "STKaiti"
    author = "Kaiti SC"
    footer = "Songti SC"
    contents = "Songti SC"
    context = "Songti SC"
    math = "Kaiti SC"
    ending = "STKaiti"

[sizes.en]
    author = 14
    title = 40
    context = 10.5
    footer = 10
    ending = 50

[sizes.zh]
    author = 14
    title = 40
    context = 10.5
    footer = 10
    ending = 50

[spaces.en]
    par-indent = 2
    par-leading = 1
    par-spacing = 1
    list-indent = 1.2
    block-above = 1
    block-below = 1
    contents-indent = 2

[spaces.zh]
    par-indent = 2
    par-leading = 1
    par-spacing = 1
    list-indent = 1.2
    block-above = 1
    block-below = 1
    contents-indent = 2
